export const FETCH_TOP_ANIME = 'FETCH_TOPS_ANIME';
export const FETCH_TOP_MANGA = 'FETCH_TOPS_MANGA';
export const FETCH_ANIME_DETAILS = 'FETCH_ANIME_DETAILS';
export const FETCH_SEASON_ANIME = 'FETCH_SEASON_ANIME';